### ISSUE TITLE
Frontend - Datos del Uservoice

### ISSUE THREAD

**Issue by carlos-segovia** [robert-dm/todosalacancha#182]
El uservoice tiene la info de kit vuelta al cole, hay que hablar con BE para que lo vean
![image](https://user-images.githubusercontent.com/34341691/39761112-9563bcc4-52ad-11e8-9352-00ad6ecfe035.png)

**Comment by robertmurer** [comment]
Me fijé en el admin de user voice y no tienen otro "Agente" para utilizar, así que creo que deberían usar el mismo.  Le mandé consulta a Gastón para que avise.
